"""Generated tag constants; do not edit by hand."""

SCHEMA_NAMESPACE = "model"
SCHEMA_VERSION = 2

IRI = 1
ENTITY = 2
ANONYMOUS_INDIVIDUAL = 3
LITERAL = 4
ANNOTATION = 5
OBJECT_INVERSE_OF = 10
OBJECT_PROPERTY_CHAIN = 11
FACET_RESTRICTION = 20
DATA_INTERSECTION_OF = 21
DATA_UNION_OF = 22
DATA_COMPLEMENT_OF = 23
DATA_ONE_OF = 24
DATATYPE_RESTRICTION = 25
OBJECT_INTERSECTION_OF = 30
OBJECT_UNION_OF = 31
OBJECT_COMPLEMENT_OF = 32
OBJECT_ONE_OF = 33
OBJECT_SOME_VALUES_FROM = 34
OBJECT_ALL_VALUES_FROM = 35
OBJECT_HAS_VALUE = 36
OBJECT_HAS_SELF = 37
OBJECT_MIN_CARDINALITY = 38
OBJECT_MAX_CARDINALITY = 39
OBJECT_EXACT_CARDINALITY = 40
DATA_SOME_VALUES_FROM = 41
DATA_ALL_VALUES_FROM = 42
DATA_HAS_VALUE = 43
DATA_MIN_CARDINALITY = 44
DATA_MAX_CARDINALITY = 45
DATA_EXACT_CARDINALITY = 46
DECLARATION = 60
SUB_CLASS_OF = 61
EQUIVALENT_CLASSES = 62
DISJOINT_CLASSES = 63
DISJOINT_UNION = 64
SUB_OBJECT_PROPERTY_OF = 70
EQUIVALENT_OBJECT_PROPERTIES = 71
DISJOINT_OBJECT_PROPERTIES = 72
INVERSE_OBJECT_PROPERTIES = 73
OBJECT_PROPERTY_DOMAIN = 74
OBJECT_PROPERTY_RANGE = 75
FUNCTIONAL_OBJECT_PROPERTY = 76
INVERSE_FUNCTIONAL_OBJECT_PROPERTY = 77
REFLEXIVE_OBJECT_PROPERTY = 78
IRREFLEXIVE_OBJECT_PROPERTY = 79
SYMMETRIC_OBJECT_PROPERTY = 80
ASYMMETRIC_OBJECT_PROPERTY = 81
TRANSITIVE_OBJECT_PROPERTY = 82
SUB_DATA_PROPERTY_OF = 90
EQUIVALENT_DATA_PROPERTIES = 91
DISJOINT_DATA_PROPERTIES = 92
DATA_PROPERTY_DOMAIN = 93
DATA_PROPERTY_RANGE = 94
FUNCTIONAL_DATA_PROPERTY = 95
DATATYPE_DEFINITION = 100
HAS_KEY = 101
SAME_INDIVIDUAL = 110
DIFFERENT_INDIVIDUALS = 111
CLASS_ASSERTION = 112
OBJECT_PROPERTY_ASSERTION = 113
NEGATIVE_OBJECT_PROPERTY_ASSERTION = 114
DATA_PROPERTY_ASSERTION = 115
NEGATIVE_DATA_PROPERTY_ASSERTION = 116
ANNOTATION_ASSERTION = 120
SUB_ANNOTATION_PROPERTY_OF = 121
ANNOTATION_PROPERTY_DOMAIN = 122
ANNOTATION_PROPERTY_RANGE = 123
VARIABLE = 140
CLASS_ATOM = 141
DATA_RANGE_ATOM = 142
OBJECT_PROPERTY_ATOM = 143
DATA_PROPERTY_ATOM = 144
BUILT_IN_ATOM = 145
SAME_INDIVIDUAL_ATOM = 146
DIFFERENT_INDIVIDUALS_ATOM = 147
SWRL_RULE = 148

__all__ = [
    "ANNOTATION",
    "ANNOTATION_ASSERTION",
    "ANNOTATION_PROPERTY_DOMAIN",
    "ANNOTATION_PROPERTY_RANGE",
    "ANONYMOUS_INDIVIDUAL",
    "ASYMMETRIC_OBJECT_PROPERTY",
    "BUILT_IN_ATOM",
    "CLASS_ASSERTION",
    "CLASS_ATOM",
    "DATATYPE_DEFINITION",
    "DATATYPE_RESTRICTION",
    "DATA_ALL_VALUES_FROM",
    "DATA_COMPLEMENT_OF",
    "DATA_EXACT_CARDINALITY",
    "DATA_HAS_VALUE",
    "DATA_INTERSECTION_OF",
    "DATA_MAX_CARDINALITY",
    "DATA_MIN_CARDINALITY",
    "DATA_ONE_OF",
    "DATA_PROPERTY_ASSERTION",
    "DATA_PROPERTY_ATOM",
    "DATA_PROPERTY_DOMAIN",
    "DATA_PROPERTY_RANGE",
    "DATA_RANGE_ATOM",
    "DATA_SOME_VALUES_FROM",
    "DATA_UNION_OF",
    "DECLARATION",
    "DIFFERENT_INDIVIDUALS",
    "DIFFERENT_INDIVIDUALS_ATOM",
    "DISJOINT_CLASSES",
    "DISJOINT_DATA_PROPERTIES",
    "DISJOINT_OBJECT_PROPERTIES",
    "DISJOINT_UNION",
    "ENTITY",
    "EQUIVALENT_CLASSES",
    "EQUIVALENT_DATA_PROPERTIES",
    "EQUIVALENT_OBJECT_PROPERTIES",
    "FACET_RESTRICTION",
    "FUNCTIONAL_DATA_PROPERTY",
    "FUNCTIONAL_OBJECT_PROPERTY",
    "HAS_KEY",
    "INVERSE_FUNCTIONAL_OBJECT_PROPERTY",
    "INVERSE_OBJECT_PROPERTIES",
    "IRI",
    "IRREFLEXIVE_OBJECT_PROPERTY",
    "LITERAL",
    "NEGATIVE_DATA_PROPERTY_ASSERTION",
    "NEGATIVE_OBJECT_PROPERTY_ASSERTION",
    "OBJECT_ALL_VALUES_FROM",
    "OBJECT_COMPLEMENT_OF",
    "OBJECT_EXACT_CARDINALITY",
    "OBJECT_HAS_SELF",
    "OBJECT_HAS_VALUE",
    "OBJECT_INTERSECTION_OF",
    "OBJECT_INVERSE_OF",
    "OBJECT_MAX_CARDINALITY",
    "OBJECT_MIN_CARDINALITY",
    "OBJECT_ONE_OF",
    "OBJECT_PROPERTY_ASSERTION",
    "OBJECT_PROPERTY_ATOM",
    "OBJECT_PROPERTY_CHAIN",
    "OBJECT_PROPERTY_DOMAIN",
    "OBJECT_PROPERTY_RANGE",
    "OBJECT_SOME_VALUES_FROM",
    "OBJECT_UNION_OF",
    "REFLEXIVE_OBJECT_PROPERTY",
    "SAME_INDIVIDUAL",
    "SAME_INDIVIDUAL_ATOM",
    "SCHEMA_NAMESPACE",
    "SCHEMA_VERSION",
    "SUB_ANNOTATION_PROPERTY_OF",
    "SUB_CLASS_OF",
    "SUB_DATA_PROPERTY_OF",
    "SUB_OBJECT_PROPERTY_OF",
    "SWRL_RULE",
    "SYMMETRIC_OBJECT_PROPERTY",
    "TRANSITIVE_OBJECT_PROPERTY",
    "VARIABLE",
]
