"""Generate and check the frozen WP17 encoded-view and version ledgers."""

from __future__ import annotations

import argparse
import json
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import cast

from pyowl_core.backends.native_views import (
    ENCODED_STRUCTURAL_DESCRIPTOR_SHA256_V1,
    ENCODED_STRUCTURAL_DESCRIPTOR_V1,
)


def _quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def _descriptor_tree() -> Mapping[str, object]:
    loaded = json.loads(ENCODED_STRUCTURAL_DESCRIPTOR_V1)
    if not isinstance(loaded, dict):  # pragma: no cover - frozen constant
        raise AssertionError("encoded descriptor must be a JSON object")
    tree = cast(dict[str, object], loaded)
    rendered = json.dumps(tree, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
    if rendered.encode("ascii") != ENCODED_STRUCTURAL_DESCRIPTOR_V1:
        raise AssertionError("encoded descriptor is not canonical JSON")
    return tree


def _table_rows(tree: Mapping[str, object], name: str) -> tuple[Mapping[str, object], ...]:
    raw = tree[name]
    if not isinstance(raw, list):  # pragma: no cover - frozen constant
        raise AssertionError(f"descriptor {name} must be a list")
    rows: list[Mapping[str, object]] = []
    for value in cast(list[object], raw):
        if not isinstance(value, dict):  # pragma: no cover - frozen constant
            raise AssertionError(f"descriptor {name} rows must be objects")
        rows.append(cast(dict[str, object], value))
    return tuple(rows)


def render_encoded_view_schema() -> str:
    """Render the checked-in schema ledger from the canonical descriptor."""

    tree = _descriptor_tree()
    lines = [
        "# Generated by `python -m tools.schema.encoded_view generate`; do not hand edit.",
        "schema = 1",
        f"name = {_quote(cast(str, tree['schema_name']))}",
        'status = "frozen-advertised"',
        'descriptor_format = "canonical-json-sorted-keys-compact-ascii"',
        f'descriptor_sha256 = "{ENCODED_STRUCTURAL_DESCRIPTOR_SHA256_V1.hex()}"',
        f"model_schema = {cast(int, tree['model_schema'])}",
        f"byte_order = {_quote(cast(str, tree['byte_order']))}",
        "id_width = 32",
        "offset_width = 64",
        'producer_input = "public OntologyView scalar traversal"',
        "capability_advertised = true",
        "",
        "[selection]",
        'scopes = ["root", "closure", "document"]',
        'document_key = "required exactly for document scope"',
        'root_sources = ["ontology_annotations", "iter_axioms", "iter_extensions"]',
        "",
        "[root_validation]",
        "[identity]",
        f"dense_ids = {_quote(cast(str, tree['dense_id_order']))}",
        f"root_order = {_quote(cast(str, tree['root_order']))}",
        f"field_rows = {_quote(cast(str, tree['field_rows']))}",
        "structural_equality_is_identity = true",
        "",
        "[ownership]",
        "exact_owner_identity = true",
        "strong_owner_retention = true",
        "buffers_readonly = true",
        "buffers_c_contiguous = true",
        'buffer_format = "B"',
        "",
        "[validation]",
        "unknown_tags_fail_closed = true",
        "unknown_buffers_fail_closed = true",
        "canonical_decode_required = true",
        "all_nodes_reachable = true",
        "duplicate_roots_fail_closed = true",
        "fingerprint_covers_descriptor_and_buffers = true",
        'limits = "owner ParseLimits tightened by request limits"',
        'untrusted_exporters = "copied to immutable bytes before publication"',
        (
            'trusted_zero_copy = "module-owned producer token; '
            'native and mapped paths require registration"'
        ),
        "",
        "[segments]",
        'local_buffers = "enclosing direct/delta/bridge normalized graph"',
        'referenced_buffers = "strongly retained validated source view"',
        'postings = "sorted unique source-local u32 root IDs"',
        "acyclic = true",
        "source_fingerprint_verified = true",
        "duplicate_member_tokens_fail_closed = true",
    ]
    root_tag_rules = tree["root_tag_rules"]
    if not isinstance(root_tag_rules, dict):  # pragma: no cover - frozen constant
        raise AssertionError("root tag rules must be an object")
    root_rule_lines = []
    for key in sorted(cast(dict[str, object], root_tag_rules)):
        raw_values = cast(dict[str, object], root_tag_rules)[key]
        if not isinstance(raw_values, list):  # pragma: no cover - frozen constant
            raise AssertionError("root tag rule values must be lists")
        values = cast(list[object], raw_values)
        root_rule_lines.append(f"{key} = [{', '.join(json.dumps(value) for value in values)}]")
    root_rule_lines.append("")
    identity_index = lines.index("[identity]")
    lines[identity_index:identity_index] = root_rule_lines
    segment_rules = tree["segment_rules"]
    if not isinstance(segment_rules, dict):  # pragma: no cover - frozen constant
        raise AssertionError("segment rules must be an object")
    for key in sorted(cast(dict[str, str], segment_rules)):
        lines.append(f"{key}_rule = {_quote(cast(dict[str, str], segment_rules)[key])}")
    for row in _table_rows(tree, "buffers"):
        lines.extend(
            [
                "",
                "[[buffers]]",
                f"name = {_quote(cast(str, row['name']))}",
                f"item_width = {cast(int, row['item_width'])}",
                f"scalar = {_quote(cast(str, row['scalar']))}",
            ]
        )
    for row in _table_rows(tree, "component_kinds"):
        lines.extend(
            [
                "",
                "[[component_kinds]]",
                f"name = {_quote(cast(str, row['name']))}",
                f"value = {cast(int, row['value'])}",
            ]
        )
    for row in _table_rows(tree, "root_kinds"):
        lines.extend(
            [
                "",
                "[[root_kinds]]",
                f"name = {_quote(cast(str, row['name']))}",
                f"value = {cast(int, row['value'])}",
            ]
        )
    for row in _table_rows(tree, "segment_fields"):
        lines.extend(
            [
                "",
                "[[segment_fields]]",
                f"name = {_quote(cast(str, row['name']))}",
                f"type = {_quote(cast(str, row['type']))}",
            ]
        )
    for table_name in ("segment_roles", "segment_posting_modes"):
        for row in _table_rows(tree, table_name):
            lines.extend(
                [
                    "",
                    f"[[{table_name}]]",
                    f"name = {_quote(cast(str, row['name']))}",
                    f"value = {cast(int, row['value'])}",
                ]
            )
    for row in _table_rows(tree, "constructors"):
        raw_fields = row["fields"]
        if not isinstance(raw_fields, list):  # pragma: no cover - frozen constant
            raise AssertionError("constructor fields must be a list")
        fields = cast(list[str], raw_fields)
        lines.extend(
            [
                "",
                "[[constructors]]",
                f"tag = {cast(int, row['tag'])}",
                f"name = {_quote(cast(str, row['name']))}",
                f"category = {_quote(cast(str, row['category']))}",
                f"fields = [{', '.join(_quote(field) for field in fields)}]",
            ]
        )
    return "\n".join(lines) + "\n"


def render_encoded_view_descriptor() -> bytes:
    """Render the exact canonical descriptor consumed by native builds."""

    _descriptor_tree()
    return ENCODED_STRUCTURAL_DESCRIPTOR_V1


def render_version_decision() -> str:
    """Render the promoted WP17 version decision."""

    return "\n".join(
        (
            "# Generated by `python -m tools.schema.encoded_view generate`; do not hand edit.",
            "schema = 1",
            'decision_id = "WP17-encoded-structural-view-v1"',
            'status = "frozen-advertised"',
            'encoded_schema_name = "pyowl-core/structural-columns"',
            "encoded_schema_version = 1",
            f'descriptor_sha256 = "{ENCODED_STRUCTURAL_DESCRIPTOR_SHA256_V1.hex()}"',
            "model_schema = 1",
            "api_version = [0, 1]",
            "adapter_protocol = 1",
            "wire_format = [1, 1]",
            'package_version = "0.1.0"',
            "capability_advertised = true",
            'promotion_owner = "WP17"',
            "",
            "[public_contract]",
            (
                'descriptor_digest_export = '
                '"pyowl_core.ENCODED_STRUCTURAL_DESCRIPTOR_SHA256_V1"'
            ),
            (
                'request_type_digest_attribute = '
                '"pyowl_core.EncodedStructuralView.DESCRIPTOR_SHA256"'
            ),
            'descriptor_digest_type = "exact immutable bytes32"',
            "materialization_required = false",
            "",
            "[amendment]",
            'id = "WP17-V1-anonymous-scope-map"',
            'phase = "pre-advertisement"',
            'decision = "retain schema version 1"',
            (
                'reason = "segmented composites require explicit current-to-effective '
                'anonymous scope mappings for canonical parity"'
            ),
            (
                'field = "anonymous_scope_map: sorted unique readonly 64-byte '
                'source-current/effective-target rows"'
            ),
            'fingerprint = "covers exact anonymous_scope_map bytes"',
            "",
            "[decisions]",
            'encoded_schema = "freeze candidate v1"',
            'api_version = "unchanged"',
            'adapter_protocol = "unchanged"',
            'model_schema = "unchanged"',
            'wire_format = "unchanged"',
            'package_version = "unchanged"',
            'capability = "advertise structural-columns v1 after installed-wheel gates"',
            "",
            "[compatibility]",
            'minimum_consumer_action = "validate exact descriptor and retain exact owner"',
            'cache_rule = "dense IDs are view-local and forbidden in persistent consumer caches"',
            'fallback_rule = "unsupported schema or tag fails closed to scalar traversal"',
            (
                'untrusted_buffer_rule = "copy before publish; '
                'registered native zero-copy is separate"'
            ),
            (
                'segment_rule = "v1 freezes direct/base/delta/member/bridge roles '
                'and local root postings"'
            ),
            "",
        )
    )


def check_generated_ledgers(root: Path) -> tuple[str, ...]:
    """Return deterministic drift errors for both generated ledgers and constants."""

    import pyowl_core

    errors: list[str] = []
    expected_files = {
        root / "schemas" / "encoded-view-v1.json": render_encoded_view_descriptor(),
        root / "schemas" / "encoded-view-v1.toml": render_encoded_view_schema(),
        root / "schemas" / "version-decision-v1.toml": render_version_decision(),
    }
    for path, expected in expected_files.items():
        try:
            observed = path.read_bytes() if isinstance(expected, bytes) else path.read_text(
                encoding="utf-8"
            )
        except OSError:
            errors.append(f"missing generated ledger: {path.relative_to(root)}")
        else:
            if observed != expected:
                errors.append(f"generated ledger is stale: {path.relative_to(root)}")
    runtime = (
        pyowl_core.API_VERSION,
        pyowl_core.ADAPTER_PROTOCOL_VERSION,
        pyowl_core.MODEL_SCHEMA_VERSION,
        pyowl_core.WIRE_FORMAT_VERSION,
        pyowl_core.__version__,
    )
    expected_runtime = ((0, 1), 1, 1, (1, 1), "0.1.0")
    if runtime != expected_runtime:
        errors.append(f"runtime version decision drifted: {runtime!r}")
    return tuple(errors)


def _write_generated_ledgers(root: Path) -> None:
    text_targets = {
        root / "schemas" / "encoded-view-v1.toml": render_encoded_view_schema(),
        root / "schemas" / "version-decision-v1.toml": render_version_decision(),
    }
    for path, content in text_targets.items():
        path.write_text(content, encoding="utf-8", newline="\n")
    (root / "schemas" / "encoded-view-v1.json").write_bytes(
        render_encoded_view_descriptor()
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("check", "generate"))
    arguments = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[2]
    if arguments.command == "generate":
        _write_generated_ledgers(root)
        return 0
    errors = check_generated_ledgers(root)
    for error in errors:
        print(error)
    return int(bool(errors))


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "check_generated_ledgers",
    "main",
    "render_encoded_view_descriptor",
    "render_encoded_view_schema",
    "render_version_decision",
]
