"""Generate and check the frozen native snapshot publication V2 ledger."""

from __future__ import annotations

import argparse
import json
import re
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import cast

from pyowl_core.backends.native_handoff_v2 import (
    NATIVE_SNAPSHOT_PUBLICATION_LEDGER_SHA256_V2,
    native_snapshot_publication_schema_semantics_v2,
)

_BARE_KEY = re.compile(r"^[A-Za-z0-9_-]+$")
_GENERATED_HEADER = (
    "# Generated by `python -m tools.schema.native_snapshot_publication_v2 generate`; "
    "do not hand edit."
)


def _key(value: str) -> str:
    return value if _BARE_KEY.fullmatch(value) else json.dumps(value, ensure_ascii=True)


def _inline(value: object) -> str:
    if type(value) is bool:
        return "true" if value else "false"
    if type(value) is int:
        return str(value)
    if type(value) is str:
        return json.dumps(value, ensure_ascii=True)
    if type(value) is list:
        return "[" + ", ".join(_inline(item) for item in value) + "]"
    if type(value) is dict:
        entries = (
            f"{_key(name)} = {_inline(item)}"
            for name, item in cast(dict[str, object], value).items()
        )
        return "{ " + ", ".join(entries) + " }"
    raise TypeError(f"unsupported native V2 ledger value: {type(value).__qualname__}")


def _render_table(
    lines: list[str],
    path: tuple[str, ...],
    values: Mapping[str, object],
) -> None:
    for name, value in values.items():
        if not isinstance(value, Mapping):
            lines.append(f"{_key(name)} = {_inline(value)}")
    for name, value in values.items():
        if not isinstance(value, Mapping):
            continue
        lines.extend(("", "[" + ".".join(_key(item) for item in (*path, name)) + "]"))
        _render_table(lines, (*path, name), value)


def render_native_snapshot_publication_v2_schema() -> str:
    """Render the exact typed semantic tree and its canonical ledger digest."""

    semantics = native_snapshot_publication_schema_semantics_v2()
    document: dict[str, object] = {}
    for name, value in semantics.items():
        document[name] = value
        if name == "ledger_canonicalization":
            document["ledger_sha256"] = NATIVE_SNAPSHOT_PUBLICATION_LEDGER_SHA256_V2.hex()
    lines = [_GENERATED_HEADER]
    _render_table(lines, (), document)
    return "\n".join(lines) + "\n"


def check_generated_ledger(root: Path) -> tuple[str, ...]:
    """Return a deterministic drift error when the checked-in ledger is stale."""

    path = root / "schemas" / "native-snapshot-publication-v2.toml"
    expected = render_native_snapshot_publication_v2_schema()
    try:
        observed = path.read_text(encoding="utf-8")
    except OSError:
        return (f"missing generated ledger: {path.relative_to(root)}",)
    if observed != expected:
        return (f"generated ledger is stale: {path.relative_to(root)}",)
    return ()


def _write_generated_ledger(root: Path) -> None:
    path = root / "schemas" / "native-snapshot-publication-v2.toml"
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        render_native_snapshot_publication_v2_schema(),
        encoding="utf-8",
        newline="\n",
    )
    temporary.replace(path)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("check", "generate"))
    arguments = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[2]
    if arguments.command == "generate":
        _write_generated_ledger(root)
        return 0
    errors = check_generated_ledger(root)
    for error in errors:
        print(error)
    return int(bool(errors))


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "check_generated_ledger",
    "main",
    "render_native_snapshot_publication_v2_schema",
]
