"""Reusable immutable syntax-only indexes over ontology views."""

from .annotations import (
    AnnotationAssertionIndex,
    AnnotationAssertionOptions,
    AnnotationAssertionPosting,
    NestedAnnotationOccurrence,
)
from .axiom_types import (
    CATEGORY_TYPES,
    AxiomCategory,
    AxiomPosting,
    AxiomTypeIndex,
    AxiomTypeOptions,
)
from .cache import (
    CacheRetention,
    IndexBuildBudget,
    IndexCachePolicy,
    IndexCacheReport,
    StructuralViewFactory,
    ViewBuildReport,
    ViewBuildStrategy,
    clear_index_cache,
    configure_index_cache,
    index_cache_report,
)
from .common import (
    FIELD_ROLE_TABLE,
    ConstructorPath,
    ConstructorPathStep,
    FieldID,
    ReferenceRole,
    ScopedIndexOptions,
)
from .declarations import (
    DeclarationIndex,
    DeclarationOptions,
    DeclarationPosting,
)
from .domains import (
    DomainRangeKind,
    DomainRangeProperty,
    DomainRangeRecord,
    DomainRangeValue,
    NamedDomainRangeResult,
    PropertyDomainRangeOptions,
    PropertyDomainRangeView,
)
from .expressions import (
    Expression,
    ExpressionOccurrence,
    ExpressionOccurrenceIndex,
    ExpressionOccurrenceOptions,
)
from .hierarchy import (
    AssertedClassHierarchyView,
    AssertedPropertyHierarchyView,
    ClassComponent,
    ClassEquivalenceRecord,
    ClassHierarchyEdge,
    ClassHierarchyNode,
    ClassHierarchyOptions,
    EquivalenceHandling,
    InversePropertyRecord,
    PropertyChainRecord,
    PropertyComponent,
    PropertyEquivalenceRecord,
    PropertyHierarchyEdge,
    PropertyHierarchyNode,
    PropertyHierarchyOptions,
)
from .identities import (
    OntologyDocumentIdentity,
    OntologyIdentityIndex,
    OntologyIdentityOptions,
)
from .references import (
    EntityReferenceIndex,
    EntityReferenceOptions,
    ReferenceKey,
    ReferenceOccurrence,
)
from .signature import SignatureOptions, SignatureView

__all__ = [
    "CATEGORY_TYPES",
    "FIELD_ROLE_TABLE",
    "AnnotationAssertionIndex",
    "AnnotationAssertionOptions",
    "AnnotationAssertionPosting",
    "AssertedClassHierarchyView",
    "AssertedPropertyHierarchyView",
    "AxiomCategory",
    "AxiomPosting",
    "AxiomTypeIndex",
    "AxiomTypeOptions",
    "CacheRetention",
    "ClassComponent",
    "ClassEquivalenceRecord",
    "ClassHierarchyEdge",
    "ClassHierarchyNode",
    "ClassHierarchyOptions",
    "ConstructorPath",
    "ConstructorPathStep",
    "DeclarationIndex",
    "DeclarationOptions",
    "DeclarationPosting",
    "DomainRangeKind",
    "DomainRangeProperty",
    "DomainRangeRecord",
    "DomainRangeValue",
    "EntityReferenceIndex",
    "EntityReferenceOptions",
    "EquivalenceHandling",
    "Expression",
    "ExpressionOccurrence",
    "ExpressionOccurrenceIndex",
    "ExpressionOccurrenceOptions",
    "FieldID",
    "IndexBuildBudget",
    "IndexCachePolicy",
    "IndexCacheReport",
    "InversePropertyRecord",
    "NamedDomainRangeResult",
    "NestedAnnotationOccurrence",
    "OntologyDocumentIdentity",
    "OntologyIdentityIndex",
    "OntologyIdentityOptions",
    "PropertyChainRecord",
    "PropertyComponent",
    "PropertyDomainRangeOptions",
    "PropertyDomainRangeView",
    "PropertyEquivalenceRecord",
    "PropertyHierarchyEdge",
    "PropertyHierarchyNode",
    "PropertyHierarchyOptions",
    "ReferenceKey",
    "ReferenceOccurrence",
    "ReferenceRole",
    "ScopedIndexOptions",
    "SignatureOptions",
    "SignatureView",
    "StructuralViewFactory",
    "ViewBuildReport",
    "ViewBuildStrategy",
    "clear_index_cache",
    "configure_index_cache",
    "index_cache_report",
]
