"""Immutable document contracts."""

from .composite import CompositeMember, OntologyComposite, compose_views
from .delta import DeltaPolicy, OntologyDelta
from .document import Fingerprint, OntologyDocument, OntologyID
from .fingerprint import (
    StructuralContext,
    StructuralContextKind,
    document_fingerprint,
    effective_structural_fingerprint,
    logical_fingerprint,
    signature_fingerprint,
    snapshot_structural_fingerprint,
)
from .imports import (
    AcquiredImport,
    AcquisitionCache,
    DocumentInput,
    DocumentRecord,
    DocumentStatus,
    ImportEdge,
    ImportManifest,
    ImportStatus,
    ParsedDocumentCache,
    SnapshotLoader,
    clear_import_caches,
)
from .overlay import OntologyOverlay, apply_delta
from .provenance import (
    DetectionBasis,
    DigestKind,
    DocumentProvenance,
    OriginIndex,
    OriginOccurrence,
    RDFMappingReport,
    RDFTripleEvidence,
    SourceMap,
    SourceOccurrence,
)
from .snapshot import (
    AxiomScope,
    CoreCapabilities,
    LoadReport,
    OntologyInput,
    OntologySnapshot,
    OntologyView,
    SnapshotProvider,
)

__all__ = [
    "AcquiredImport",
    "AcquisitionCache",
    "AxiomScope",
    "CompositeMember",
    "CoreCapabilities",
    "DeltaPolicy",
    "DetectionBasis",
    "DigestKind",
    "DocumentInput",
    "DocumentProvenance",
    "DocumentRecord",
    "DocumentStatus",
    "Fingerprint",
    "ImportEdge",
    "ImportManifest",
    "ImportStatus",
    "LoadReport",
    "OntologyComposite",
    "OntologyDelta",
    "OntologyDocument",
    "OntologyID",
    "OntologyInput",
    "OntologyOverlay",
    "OntologySnapshot",
    "OntologyView",
    "OriginIndex",
    "OriginOccurrence",
    "ParsedDocumentCache",
    "RDFMappingReport",
    "RDFTripleEvidence",
    "SnapshotLoader",
    "SnapshotProvider",
    "SourceMap",
    "SourceOccurrence",
    "StructuralContext",
    "StructuralContextKind",
    "apply_delta",
    "clear_import_caches",
    "compose_views",
    "document_fingerprint",
    "effective_structural_fingerprint",
    "logical_fingerprint",
    "signature_fingerprint",
    "snapshot_structural_fingerprint",
]
