"""Curated public contracts for the shared Java-free OWL 2 kernel."""

from __future__ import annotations

from . import index as index
from . import model as model
from .api import (
    DocumentInput,
    OntologyDelta,
    OntologyInput,
    apply_delta,
    coerce_snapshot,
    compose_views,
    decode_snapshot,
    encode_snapshot,
    load_snapshot,
    open_snapshot,
    parse_document,
    write_snapshot,
)
from .backends.python import PythonParser
from .cancellation import CancellationSource, CancellationToken
from .config import BackendPreference, DocumentFormat, ImportPolicy, LoadOptions
from .diagnostics import Diagnostic, DiagnosticScalar, Severity, SourceSpan
from .document import (
    AcquiredImport,
    AcquisitionCache,
    AxiomScope,
    CompositeMember,
    CoreCapabilities,
    DeltaPolicy,
    DetectionBasis,
    DigestKind,
    DocumentProvenance,
    DocumentRecord,
    DocumentStatus,
    Fingerprint,
    ImportEdge,
    ImportManifest,
    ImportStatus,
    LoadReport,
    OntologyComposite,
    OntologyDocument,
    OntologyID,
    OntologyOverlay,
    OntologySnapshot,
    OntologyView,
    OriginIndex,
    OriginOccurrence,
    ParsedDocumentCache,
    RDFMappingReport,
    RDFTripleEvidence,
    SnapshotLoader,
    SnapshotProvider,
    SourceMap,
    SourceOccurrence,
    StructuralContext,
    StructuralContextKind,
    clear_import_caches,
    document_fingerprint,
    effective_structural_fingerprint,
    logical_fingerprint,
    signature_fingerprint,
    snapshot_structural_fingerprint,
)
from .exceptions import (
    AccessDeniedError,
    AdapterCompatibilityError,
    AdapterError,
    BackendError,
    BackendProtocolError,
    BackendUnavailableError,
    ClosedSnapshotError,
    DeltaBaseMismatchError,
    DeltaError,
    DeprecatedAPIWarning,
    DocumentIdentityConflictError,
    FormatDetectionError,
    FormatGuessWarning,
    ImportCycleError,
    ImportResolutionError,
    IntegrityError,
    InvalidIRIError,
    InvalidLiteralError,
    LossyRenderWarning,
    ModelError,
    NativeBackendUnavailableWarning,
    OntologySyntaxError,
    OperationCancelledError,
    OptionConflictError,
    OverlayPerformanceWarning,
    ParseError,
    ProfileError,
    PyOWLCoreError,
    PyOWLCoreWarning,
    ReentrancyError,
    ResourceLimitError,
    SnapshotInUseError,
    SnapshotLifecycleError,
    StructuralConstraintError,
    UnresolvedImportError,
    UnresolvedImportWarning,
    UnsupportedSyntaxError,
    WireCorruptionError,
    WireError,
    WireLimitError,
    WireVersionError,
)
from .index import *  # noqa: F403
from .io.formats import FormatDetection, detect_format
from .io.formats.rendering import (
    DocumentTarget,
    LossyPolicy,
    RenderOptions,
    render_document,
    write_document,
)
from .io.resolver import (
    CatalogResolver,
    CompositeResolver,
    DirectoryNamingStrategy,
    DirectoryResolver,
    HttpAcquisitionCache,
    HttpCacheEntry,
    HttpResolver,
    ImportRequest,
    ImportResolver,
    MappingResolver,
    MappingTarget,
    ResolutionAttempt,
    ResolutionKind,
    ResolutionMode,
    ResolvedDocument,
    ResolvedSource,
    ResolverOutcome,
    resolver_configuration_fingerprint,
)
from .io.source import DocumentSource
from .limits import ParseLimits
from .model import *  # noqa: F403
from .progress import (
    ProgressBuffer,
    ProgressCallback,
    ProgressEvent,
    ProgressReporter,
    ProgressScalar,
    report_progress,
)
from .wire import (
    CacheEntry,
    CacheGCReport,
    DurabilityPolicy,
    MappedOntologySnapshot,
    SectionKind,
    WireCache,
)

__version__ = "0.1.0.dev0"

API_VERSION = (0, 1)
MODEL_SCHEMA_VERSION = 1
WIRE_FORMAT_VERSION = (1, 1)
ADAPTER_PROTOCOL_VERSION = 1

__all__ = [
    "ADAPTER_PROTOCOL_VERSION",
    "API_VERSION",
    "MODEL_SCHEMA_VERSION",
    "WIRE_FORMAT_VERSION",
    "AccessDeniedError",
    "AcquiredImport",
    "AcquisitionCache",
    "AdapterCompatibilityError",
    "AdapterError",
    "BackendError",
    "BackendPreference",
    "BackendProtocolError",
    "BackendUnavailableError",
    "AxiomScope",
    "CancellationSource",
    "CancellationToken",
    "CacheEntry",
    "CacheGCReport",
    "CatalogResolver",
    "ClosedSnapshotError",
    "CompositeResolver",
    "CoreCapabilities",
    "CompositeMember",
    "DeltaBaseMismatchError",
    "DeltaError",
    "DeltaPolicy",
    "DurabilityPolicy",
    "DeprecatedAPIWarning",
    "Diagnostic",
    "DiagnosticScalar",
    "DetectionBasis",
    "DigestKind",
    "DirectoryNamingStrategy",
    "DirectoryResolver",
    "DocumentInput",
    "DocumentProvenance",
    "DocumentFormat",
    "DocumentSource",
    "DocumentTarget",
    "DocumentIdentityConflictError",
    "DocumentRecord",
    "DocumentStatus",
    "FormatDetectionError",
    "FormatDetection",
    "FormatGuessWarning",
    "ImportCycleError",
    "ImportEdge",
    "ImportManifest",
    "ImportPolicy",
    "ImportRequest",
    "ImportResolver",
    "ImportResolutionError",
    "ImportStatus",
    "IntegrityError",
    "InvalidIRIError",
    "InvalidLiteralError",
    "LoadOptions",
    "LoadReport",
    "LossyPolicy",
    "LossyRenderWarning",
    "MappingResolver",
    "MappingTarget",
    "MappedOntologySnapshot",
    "ModelError",
    "NativeBackendUnavailableWarning",
    "OntologyDocument",
    "OntologyDelta",
    "OntologyComposite",
    "OntologyID",
    "OntologyInput",
    "OntologySnapshot",
    "OntologyOverlay",
    "OntologySyntaxError",
    "OntologyView",
    "OperationCancelledError",
    "OptionConflictError",
    "OverlayPerformanceWarning",
    "ParseError",
    "ParseLimits",
    "ParsedDocumentCache",
    "PythonParser",
    "ProfileError",
    "ProgressBuffer",
    "ProgressCallback",
    "ProgressEvent",
    "ProgressReporter",
    "ProgressScalar",
    "PyOWLCoreError",
    "PyOWLCoreWarning",
    "ReentrancyError",
    "ResourceLimitError",
    "ResolvedDocument",
    "ResolvedSource",
    "ResolutionAttempt",
    "ResolutionKind",
    "ResolutionMode",
    "ResolverOutcome",
    "RenderOptions",
    "RDFMappingReport",
    "RDFTripleEvidence",
    "Severity",
    "SectionKind",
    "SnapshotInUseError",
    "SnapshotLifecycleError",
    "SnapshotLoader",
    "SnapshotProvider",
    "StructuralContext",
    "StructuralContextKind",
    "SourceSpan",
    "SourceMap",
    "SourceOccurrence",
    "StructuralConstraintError",
    "UnresolvedImportError",
    "UnresolvedImportWarning",
    "UnsupportedSyntaxError",
    "WireCorruptionError",
    "WireCache",
    "WireError",
    "WireLimitError",
    "WireVersionError",
    "HttpAcquisitionCache",
    "HttpCacheEntry",
    "HttpResolver",
    "Fingerprint",
    "OriginIndex",
    "OriginOccurrence",
    "__version__",
    "apply_delta",
    "model",
    "index",
    "detect_format",
    "clear_import_caches",
    "coerce_snapshot",
    "compose_views",
    "decode_snapshot",
    "document_fingerprint",
    "effective_structural_fingerprint",
    "encode_snapshot",
    "load_snapshot",
    "logical_fingerprint",
    "open_snapshot",
    "parse_document",
    "render_document",
    "report_progress",
    "signature_fingerprint",
    "snapshot_structural_fingerprint",
    "write_document",
    "write_snapshot",
    "resolver_configuration_fingerprint",
    *index.__all__,
    *model.__all__,
]
